### ISSUE TITLE
Merge attempted to be performed on service_id when it is not included

### ISSUE THREAD

**Issue by kuanb** [UDST/urbanaccess#10]
This line calls the function `calendar_dates_agencyid `: 
https://github.com/UDST/urbanaccess/blob/master/urbanaccess/gtfs/utils_format.py#L417

A subset of the following dataframes are included as keyword arguments: `routes_df`, `trips_df`, and `agency_df`.

In the `calendar_dates_agencyid` function definition, they prior 3 dataframes are merged together and then need to be merged left onto a `calendar_dates_df` dataframe ([here](https://github.com/UDST/urbanaccess/blob/5b6fc9396ac370f2e8628bb2b63b139c677497e8/urbanaccess/gtfs/utils_format.py#L210)). The left merge states it needs to occur on `service_id`. 

At this point, the function will error out with the following: `KeyError: 'service_id'`.

Solution: Include `service_id` (for example, it exists in `trips.txt`) from one of the first 3 dataframes.

**Comment by sablanchard** [comment]
Fixed with #13
