### ISSUE TITLE
Edit to variable name in documentation, headways() positional args 

### ISSUE THREAD

**Issue by kuanb** [UDST/urbanaccess#14]
In both the code and the documentation for `urbanaccess.gtfs.load.gtfsfeed_to_df`, the return variable is called `gtfsfeeds_df`. 

This is a bit confusing as the appending of `_df` typically indicates that the variable is a dataframe. In this case, it is not - it is a dictionary containing dataframes. Perhaps a better name would be `gtfsfeeds_dict` or `gtfsfeeds_dfs_dict`. 

This naming convention could also be carried over to `urbanaccess.gtfs.headways.headways`, where the parameter `gtfsfeeds_df` could be similarly renamed.

11:10 AM PST  - Edit: In the above I refer to the response as a dictionary when I realize it is an object instantiated from the class described in [this file](https://github.com/UDST/urbanaccess/blob/master/urbanaccess/gtfs/gtfsfeeds_dataframe.py). That said, some rename still would be very helpful in clarifying that it is not a dataframe.

**Comment by sablanchard** [comment]
Great point, would something like `gtfsfeeds_dfs` be sufficient?

**Comment by kuanb** [comment]
Yeah I think that would be helpful!

**Comment by sablanchard** [comment]
Great! Will make the change in a upcoming PR.

**Comment by pksohn** [comment]
Addressed with #17.
