### ISSUE TITLE
Add integration tests to CI builds

### ISSUE THREAD

**Issue by pksohn** [UDST/urbanaccess#19]
We should include scripts that run a "full" workflow to Travis CI builds with a good number of regions with different data schemas and varying degrees of data cleanliness. I think it would help catch the kind of edge cases that are coming up now.

**Comment by sablanchard** [comment]
@pksohn added full workflow (w variations) for 3 different regions with varying gtfs structure types in PR #30

**Comment by sablanchard** [comment]
added integration tests to CI builds with #30
