### ISSUE TITLE
Why sklearn vs scikit-learn?

### ISSUE THREAD

**Issue by kuanb** [UDST/urbanaccess#27]
[Ques] According to the package page, one should use scikit-learn, rather than sklearn. Is there a specific reason why sklearn is being used, instead?

Ref: https://pypi.python.org/pypi/sklearn/0.0

**Comment by pksohn** [comment]
Hey Kuan, 
The list of [required packages](https://github.com/UDST/urbanaccess/blob/master/setup.py#L38) in setup.py refers to the right package, `scikit-learn`. The import syntax just uses the shortened name, `sklearn`, as seen in the [quick start guide](http://scikit-learn.org/stable/tutorial/basic/tutorial.html). 

Closing this for now - let us know if there's something we missed here.

**Comment by kuanb** [comment]
Ah I see it was updated a few days ago: https://github.com/UDST/urbanaccess/commit/ff1cfe91c096f2e9c3622733486436cea62aa3ae

**Comment by pksohn** [comment]
Ah, that makes sense :)
