### ISSUE TITLE
Kernel appears to have died when saving h5 

### ISSUE THREAD

**Issue by rxl204** [UDST/urbanaccess#57]
Please note that while GTFS feeds are a standardized format, not all transit services follow the same data standards or supply all of the necessary information in their GTFS feed that are required for UrbanAccess to compute a travel time weighted graph.  UrbanAccess attempts to deal with the most common GTFS feed data schema issues however it is expected some GTFS feeds may raise errors or may not fit the expected data schema. If you encounter a bug in UrbanAccess please: 1) first search the previously opened issues to see if the problem has already been reported; 2) If not, fill in the template below and tag with the appropriate `Type` label (and `Data` label if applicable). You can delete any sections that do not apply.

#### GTFS feed or OSM data (optional) 
If the issue is related to a specific GTFS feed or OSM data please provide the URL to download the GTFS feed or the bounding box used to extract the OSM data.

#### Environment 

- Operating system: Windows

- Python version: 2

- UrbanAccess version: '0.2.0'

- UrbanAccess required packages versions (optional):

#### Paste the code that reproduces the issue here:

```python
ua.network.save_network(urbanaccess_network=urbanaccess_net,
                        filename='final_net.h5',
                        overwrite_key = True)
```

#### Paste the error message (if applicable):
```python
Kernel appears to have died
```

**Comment by sablanchard** [comment]
thanks for the report @rxl204 , in order to replicate the issue we will need a full working notebook or script to troubleshoot.

**Comment by rxl204** [comment]
I ran this notebook as is with no changes.
https://github.com/UDST/urbanaccess/blob/dev/demo/simple_example.ipynb
Everything ran well until i got to saving or reading the h5 files.

**Comment by sablanchard** [comment]
Hi @rxl204 ,
I ran through the demo notebook in a new Windows 64-bit python 27 conda env with urbanaccess 0.2.0 and dependencies: pandas=0.23.4 and pytables=3.4.4 and was not able to replicate the issue, it saves the network to disk fine.

Did you use conda to install `urbanaccess` and all dependencies? how much disk space do you have on your drive where you are saving the file? How much memory does your machine have? What versions of pandas and pytables do you have in your env you are running the notebook in? If you are using conda to manage your environments you can activate your conda env that you are using and do `conda list` to get your package versions.

I suggest creating a brand new conda env like this `conda create -n ua_test_p27 python=2.7 urbanaccess` to see if its a issue with a dependency and run the notebook in that env to see if you get the same issue.

However, in the meantime if you would like to continue in the notebook to run the demo saving and loading the network to and from disk is optional so feel free to skip that part so you can continue on.
