### ISSUE TITLE
Python 3 Support or Clarification

### ISSUE THREAD

**Issue by kuanb** [UDST/urbanaccess#9]
From what I understand, Pandanas was written in and only support Python 2.x (The Travis config indicates 2.7 be used in tests, for example). Because this library is built on Pandanas, I suspect is has the same constraints. If that is the case, it would be helpful to state that in the repo's `README`.

More broadly, I would be interested in hearing from those who have spent more time with Pandanas than I as to estimates on how difficult it would be to enable Pandanas to work with Python 3. If the lift is not that severe, this would be something I would be quite interested in.

**Comment by federicofernandez** [comment]
Hi Kuan, thanks for your message.
Recently, Pandana has been ported to Python3.
This is the relevant release: https://github.com/UDST/pandana/releases/tag/v0.3.0
Let us know if that doesn't answer your question.

**Comment by sablanchard** [comment]
Hi Kuan,
If your question related directly to the UrbanAccess repo, this repo is only Python 2.x compliant right now, however we are working on a Python 3 version shortly.

**Comment by kuanb** [comment]
Thanks all,
Yes the question pertains to this repo (UrbanAccess). I was just noting that I had thought Pandanas was Python 2 only, and was wondering aloud if that was the constraint on Urban Access, restricting it Python 2 only as a result.

Thanks for the responses - had not seen that Pandanas was ported; very cool!

The point of the Issue was to suggest that - if Urban Access is Python 2 only right now, it might be helpful to state that in the repo's `README`.

**Comment by sablanchard** [comment]
Thanks for the clarification Kuan. This has been addressed via commit: 9a6b9b04f530d85013ba105bf6922df89593b9d4
